	<!--Basic Scripts-->
	<script src="<%=basepath%>/static/lib/beyond/js/jquery-2.0.3.min.js"></script>
	<script src="<%=basepath%>/static/lib/js/iframeheight.js"></script>
	<!-- /Page Body -->
	<script src="<%=basepath%>/static/lib/beyond/js/bootstrap.min.js"></script>

	<!--Beyond Scripts-->
	<script src="<%=basepath%>/static/lib/beyond/js/beyond.min.js"></script>

    <!--Page Related Scripts-->
    <script src="<%=basepath%>/static/lib/beyond/js/bootbox/bootbox.js"></script>
    
    <!--Page Related Scripts-->
    <script src="<%=basepath%>/static/lib/beyond/js/toastr/toastr.js"></script>
    
    <!--Page Related Scripts-->
    <script src="<%=basepath%>/static/lib/beyond/js/validation/bootstrapValidator.min.js"></script>
     <script src="<%=basepath%>/static/lib/beyond/js/validation/language/zh_CN.js"></script>
     <!--Jquery Select2-->
    <script src="<%=basepath%>/static/lib/beyond/js/select2/select2.js"></script>
    
    <!--Bootstrap Tags Input-->
    <script src="<%=basepath%>/static/lib/beyond/js/tagsinput/bootstrap-tagsinput.js"></script>